#!/bin/bash

# System
ast-firmware                # Firmware for my laptop (Pavilion G6)
upd72020x-fw                # Firmware for my laptop (Pavilion G6)
aic94xx-firmware            # Firmware for my laptop (Pavilion G6)
wd719x-firmware             # Firmware for my laptop (Pavilion G6)

# Applications
sioyek-git                  # PDF Reader better than zathura
anki-bin                    # Powerful flashcards app

# Desktop environment
aylurs-gtk-shell            # AGS
wl-screenrec                # Screen recorder with GPU
swww                        # Nice wallpaper manager
gtklock                     # GTK Locker for wayland inspired by gtk-greet
fcitx5-skin-ori-git         # Fcitx5 ori theme

# River window manager
wideriver                   # Feature-rich river layout manager
lswt                        # List wayland top levels
ristate                     # IPC for river to integrate eww
